spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 1111
  liquibase:
    change-log: classpath:db.changelog-master.yaml